### PR TITLE
Error handling

### PR DESCRIPTION
**Pull request by omrilit**

### CODE REVIEW

**Review by hadard — APPROVED** [review]
I think this commit should be "squashed" with pre

**Comment by omrilit** [comment]
What do you mean "with pre"?

**Comment by hadard** [comment]
starting from 589643104e53b39ec300440f4cbc1e44e2ad53c0
In general, I think that in this project we can fix the history of master branch until additional developer works on it. It will help us later to follow the changes we did on this repo.

**Comment by omrilit** [comment]
Actually I pushed it in a separate PR since I think that this change will last even after the upstream will solve the account:setup command.

**Comment by omrilit** [comment]
Meanwhile I merge it in order to open the dependent Salto PR.
If you still think that I should squash them LMK.

**Pull request merged**
